version: "3.8"

services:
  postgres_db:
    build: api/database/postgres
    container_name: housekeeping_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user_keeper
      POSTGRES_PASSWORD: password_keeper
      POSTGRES_DB: db_keeper
    networks:
      - house_keeping_network
      
  housekeeper_api:
    build: api
    container_name: housekeeping_api
    ports:
      - "8000:8000"
    environment:
      FRONT_END_URL: http://ec2-54-74-203-125.eu-west-1.compute.amazonaws.com
      DB_NAME: db_keeper
      DB_USER: user_keeper
      DB_PASSWORD: password_keeper
      DB_HOST: postgres_db
      DB_PORT: 5432
      EMAIL_HOST_PASSWORD: "hbyc ljcj mjwh fpgz"
      EMAIL_HOST: smtp.gmail.com
      EMAIL_HOST_USER: rahulpoppad.1999@gmail.com
      EMAIL_USE_TLS: 1
      EMAIL_PORT: 587
      DEBUG: 0
      SECRET_KEY: d2)+*y9)pud71-n_m!qu#qx_glh(+rbat*almc!*!t9!v=w8zr25n42^q#ch!n%fe@-a+8$3=&hzd_(xvl@7ue)v)xr0wwx+*!l)
    depends_on:
      - postgres_db
    networks:
      - house_keeping_network

  housekeeper_web:
    build:
      context: web
      args:
        VITE_BACKEND_DOMAIN: ec2-54-74-203-125.eu-west-1.compute.amazonaws.com:8000
    container_name: housekeeping_web
    ports:
      - "80:80"
    networks:
      - house_keeping_network

networks:
  house_keeping_network: {}