# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB db_keeper
ENV POSTGRES_USER user_keeper
ENV POSTGRES_PASSWORD password_keeper

# Expose the default PostgreSQL port (5432)
EXPOSE 5432