--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Debian 16.2-1)
-- Dumped by pg_dump version 16.2 (Debian 16.2-1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO keeper;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO keeper;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO keeper;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO keeper;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO keeper;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO keeper;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO keeper;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO keeper;

--
-- Name: keeper_accessinfo; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.keeper_accessinfo (
    id bigint NOT NULL,
    address_name character varying(255) NOT NULL,
    address_code character varying(50) NOT NULL,
    how_to_get_in text NOT NULL,
    any_pets boolean NOT NULL,
    pets_description character varying(255),
    additional_notes text
);


ALTER TABLE public.keeper_accessinfo OWNER TO keeper;

--
-- Name: keeper_accessinfo_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.keeper_accessinfo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keeper_accessinfo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: keeper_booking; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.keeper_booking (
    id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    status character varying(20) NOT NULL,
    access_info_id bigint NOT NULL,
    user_id bigint NOT NULL,
    cleaning_frequency_id bigint NOT NULL,
    payment_id bigint
);


ALTER TABLE public.keeper_booking OWNER TO keeper;

--
-- Name: keeper_booking_cleaners; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.keeper_booking_cleaners (
    id bigint NOT NULL,
    booking_id bigint NOT NULL,
    cleaner_id bigint NOT NULL
);


ALTER TABLE public.keeper_booking_cleaners OWNER TO keeper;

--
-- Name: keeper_booking_cleaners_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.keeper_booking_cleaners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keeper_booking_cleaners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: keeper_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.keeper_booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keeper_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: keeper_booking_services; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.keeper_booking_services (
    id bigint NOT NULL,
    booking_id bigint NOT NULL,
    subservice_id bigint NOT NULL
);


ALTER TABLE public.keeper_booking_services OWNER TO keeper;

--
-- Name: keeper_booking_services_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.keeper_booking_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keeper_booking_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: keeper_cleaner; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.keeper_cleaner (
    id bigint NOT NULL,
    bio text NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.keeper_cleaner OWNER TO keeper;

--
-- Name: keeper_cleaner_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.keeper_cleaner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keeper_cleaner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: keeper_cleaningfrequency; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.keeper_cleaningfrequency (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(255) NOT NULL
);


ALTER TABLE public.keeper_cleaningfrequency OWNER TO keeper;

--
-- Name: keeper_cleaningfrequency_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.keeper_cleaningfrequency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keeper_cleaningfrequency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: keeper_cleantype; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.keeper_cleantype (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text
);


ALTER TABLE public.keeper_cleantype OWNER TO keeper;

--
-- Name: keeper_cleantype_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.keeper_cleantype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keeper_cleantype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: keeper_creditcard; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.keeper_creditcard (
    id bigint NOT NULL,
    cardholder_name character varying(255) NOT NULL,
    card_number character varying(16) NOT NULL,
    expiration_date character varying(4) NOT NULL,
    cvv character varying(4) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.keeper_creditcard OWNER TO keeper;

--
-- Name: keeper_creditcard_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.keeper_creditcard ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keeper_creditcard_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: keeper_paymentmethod; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.keeper_paymentmethod (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.keeper_paymentmethod OWNER TO keeper;

--
-- Name: keeper_paymentmethod_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.keeper_paymentmethod ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keeper_paymentmethod_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: keeper_subservice; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.keeper_subservice (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    price numeric(10,2) NOT NULL,
    clean_type_id bigint NOT NULL
);


ALTER TABLE public.keeper_subservice OWNER TO keeper;

--
-- Name: keeper_subservice_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.keeper_subservice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keeper_subservice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_onetimepassword; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.main_onetimepassword (
    id bigint NOT NULL,
    code character varying(6) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.main_onetimepassword OWNER TO keeper;

--
-- Name: main_onetimepassword_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.main_onetimepassword ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_onetimepassword_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_user; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.main_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    phone_number character varying(13) NOT NULL,
    is_active boolean NOT NULL,
    is_verified boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_superuser boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    last_login timestamp with time zone NOT NULL,
    auth_provider character varying(50) NOT NULL
);


ALTER TABLE public.main_user OWNER TO keeper;

--
-- Name: main_user_groups; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.main_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.main_user_groups OWNER TO keeper;

--
-- Name: main_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.main_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_user_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.main_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_user_user_permissions; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.main_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.main_user_user_permissions OWNER TO keeper;

--
-- Name: main_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.main_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO keeper;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: keeper
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO keeper;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: keeper
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: keeper_accessinfo keeper_accessinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_accessinfo
    ADD CONSTRAINT keeper_accessinfo_pkey PRIMARY KEY (id);


--
-- Name: keeper_booking_cleaners keeper_booking_cleaners_booking_id_cleaner_id_0c2f41ba_uniq; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_booking_cleaners
    ADD CONSTRAINT keeper_booking_cleaners_booking_id_cleaner_id_0c2f41ba_uniq UNIQUE (booking_id, cleaner_id);


--
-- Name: keeper_booking_cleaners keeper_booking_cleaners_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_booking_cleaners
    ADD CONSTRAINT keeper_booking_cleaners_pkey PRIMARY KEY (id);


--
-- Name: keeper_booking keeper_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_booking
    ADD CONSTRAINT keeper_booking_pkey PRIMARY KEY (id);


--
-- Name: keeper_booking_services keeper_booking_services_booking_id_subservice_id_544a374b_uniq; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_booking_services
    ADD CONSTRAINT keeper_booking_services_booking_id_subservice_id_544a374b_uniq UNIQUE (booking_id, subservice_id);


--
-- Name: keeper_booking_services keeper_booking_services_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_booking_services
    ADD CONSTRAINT keeper_booking_services_pkey PRIMARY KEY (id);


--
-- Name: keeper_cleaner keeper_cleaner_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_cleaner
    ADD CONSTRAINT keeper_cleaner_pkey PRIMARY KEY (id);


--
-- Name: keeper_cleaner keeper_cleaner_user_id_key; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_cleaner
    ADD CONSTRAINT keeper_cleaner_user_id_key UNIQUE (user_id);


--
-- Name: keeper_cleaningfrequency keeper_cleaningfrequency_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_cleaningfrequency
    ADD CONSTRAINT keeper_cleaningfrequency_pkey PRIMARY KEY (id);


--
-- Name: keeper_cleantype keeper_cleantype_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_cleantype
    ADD CONSTRAINT keeper_cleantype_pkey PRIMARY KEY (id);


--
-- Name: keeper_creditcard keeper_creditcard_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_creditcard
    ADD CONSTRAINT keeper_creditcard_pkey PRIMARY KEY (id);


--
-- Name: keeper_paymentmethod keeper_paymentmethod_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_paymentmethod
    ADD CONSTRAINT keeper_paymentmethod_pkey PRIMARY KEY (id);


--
-- Name: keeper_subservice keeper_subservice_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_subservice
    ADD CONSTRAINT keeper_subservice_pkey PRIMARY KEY (id);


--
-- Name: main_onetimepassword main_onetimepassword_code_key; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_onetimepassword
    ADD CONSTRAINT main_onetimepassword_code_key UNIQUE (code);


--
-- Name: main_onetimepassword main_onetimepassword_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_onetimepassword
    ADD CONSTRAINT main_onetimepassword_pkey PRIMARY KEY (id);


--
-- Name: main_onetimepassword main_onetimepassword_user_id_key; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_onetimepassword
    ADD CONSTRAINT main_onetimepassword_user_id_key UNIQUE (user_id);


--
-- Name: main_user main_user_email_key; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_user
    ADD CONSTRAINT main_user_email_key UNIQUE (email);


--
-- Name: main_user_groups main_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_user_groups
    ADD CONSTRAINT main_user_groups_pkey PRIMARY KEY (id);


--
-- Name: main_user_groups main_user_groups_user_id_group_id_ae195797_uniq; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_user_groups
    ADD CONSTRAINT main_user_groups_user_id_group_id_ae195797_uniq UNIQUE (user_id, group_id);


--
-- Name: main_user main_user_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_user
    ADD CONSTRAINT main_user_pkey PRIMARY KEY (id);


--
-- Name: main_user_user_permissions main_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_user_user_permissions
    ADD CONSTRAINT main_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: main_user_user_permissions main_user_user_permissions_user_id_permission_id_96b9fadf_uniq; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_user_user_permissions
    ADD CONSTRAINT main_user_user_permissions_user_id_permission_id_96b9fadf_uniq UNIQUE (user_id, permission_id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: keeper_booking_access_info_id_a2886cc8; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX keeper_booking_access_info_id_a2886cc8 ON public.keeper_booking USING btree (access_info_id);


--
-- Name: keeper_booking_cleaners_booking_id_684d2383; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX keeper_booking_cleaners_booking_id_684d2383 ON public.keeper_booking_cleaners USING btree (booking_id);


--
-- Name: keeper_booking_cleaners_cleaner_id_b33dc468; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX keeper_booking_cleaners_cleaner_id_b33dc468 ON public.keeper_booking_cleaners USING btree (cleaner_id);


--
-- Name: keeper_booking_cleaning_frequency_id_c4ad4d26; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX keeper_booking_cleaning_frequency_id_c4ad4d26 ON public.keeper_booking USING btree (cleaning_frequency_id);


--
-- Name: keeper_booking_payment_id_a50b6b75; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX keeper_booking_payment_id_a50b6b75 ON public.keeper_booking USING btree (payment_id);


--
-- Name: keeper_booking_services_booking_id_799c4d7a; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX keeper_booking_services_booking_id_799c4d7a ON public.keeper_booking_services USING btree (booking_id);


--
-- Name: keeper_booking_services_subservice_id_364c28a4; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX keeper_booking_services_subservice_id_364c28a4 ON public.keeper_booking_services USING btree (subservice_id);


--
-- Name: keeper_booking_user_id_e65c7314; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX keeper_booking_user_id_e65c7314 ON public.keeper_booking USING btree (user_id);


--
-- Name: keeper_creditcard_user_id_6cb02313; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX keeper_creditcard_user_id_6cb02313 ON public.keeper_creditcard USING btree (user_id);


--
-- Name: keeper_subservice_clean_type_id_8df3b20e; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX keeper_subservice_clean_type_id_8df3b20e ON public.keeper_subservice USING btree (clean_type_id);


--
-- Name: main_onetimepassword_code_1760287d_like; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX main_onetimepassword_code_1760287d_like ON public.main_onetimepassword USING btree (code varchar_pattern_ops);


--
-- Name: main_user_email_2597293b_like; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX main_user_email_2597293b_like ON public.main_user USING btree (email varchar_pattern_ops);


--
-- Name: main_user_groups_group_id_a337ba62; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX main_user_groups_group_id_a337ba62 ON public.main_user_groups USING btree (group_id);


--
-- Name: main_user_groups_user_id_df502602; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX main_user_groups_user_id_df502602 ON public.main_user_groups USING btree (user_id);


--
-- Name: main_user_user_permissions_permission_id_cd2b56a3; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX main_user_user_permissions_permission_id_cd2b56a3 ON public.main_user_user_permissions USING btree (permission_id);


--
-- Name: main_user_user_permissions_user_id_451ce57f; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX main_user_user_permissions_user_id_451ce57f ON public.main_user_user_permissions USING btree (user_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: keeper
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: keeper_booking keeper_booking_access_info_id_a2886cc8_fk_keeper_accessinfo_id; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_booking
    ADD CONSTRAINT keeper_booking_access_info_id_a2886cc8_fk_keeper_accessinfo_id FOREIGN KEY (access_info_id) REFERENCES public.keeper_accessinfo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: keeper_booking_cleaners keeper_booking_clean_booking_id_684d2383_fk_keeper_bo; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_booking_cleaners
    ADD CONSTRAINT keeper_booking_clean_booking_id_684d2383_fk_keeper_bo FOREIGN KEY (booking_id) REFERENCES public.keeper_booking(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: keeper_booking_cleaners keeper_booking_clean_cleaner_id_b33dc468_fk_keeper_cl; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_booking_cleaners
    ADD CONSTRAINT keeper_booking_clean_cleaner_id_b33dc468_fk_keeper_cl FOREIGN KEY (cleaner_id) REFERENCES public.keeper_cleaner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: keeper_booking keeper_booking_cleaning_frequency_i_c4ad4d26_fk_keeper_cl; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_booking
    ADD CONSTRAINT keeper_booking_cleaning_frequency_i_c4ad4d26_fk_keeper_cl FOREIGN KEY (cleaning_frequency_id) REFERENCES public.keeper_cleaningfrequency(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: keeper_booking keeper_booking_payment_id_a50b6b75_fk_keeper_paymentmethod_id; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_booking
    ADD CONSTRAINT keeper_booking_payment_id_a50b6b75_fk_keeper_paymentmethod_id FOREIGN KEY (payment_id) REFERENCES public.keeper_paymentmethod(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: keeper_booking_services keeper_booking_servi_booking_id_799c4d7a_fk_keeper_bo; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_booking_services
    ADD CONSTRAINT keeper_booking_servi_booking_id_799c4d7a_fk_keeper_bo FOREIGN KEY (booking_id) REFERENCES public.keeper_booking(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: keeper_booking_services keeper_booking_servi_subservice_id_364c28a4_fk_keeper_su; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_booking_services
    ADD CONSTRAINT keeper_booking_servi_subservice_id_364c28a4_fk_keeper_su FOREIGN KEY (subservice_id) REFERENCES public.keeper_subservice(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: keeper_booking keeper_booking_user_id_e65c7314_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_booking
    ADD CONSTRAINT keeper_booking_user_id_e65c7314_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: keeper_cleaner keeper_cleaner_user_id_f947fdb2_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_cleaner
    ADD CONSTRAINT keeper_cleaner_user_id_f947fdb2_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: keeper_creditcard keeper_creditcard_user_id_6cb02313_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_creditcard
    ADD CONSTRAINT keeper_creditcard_user_id_6cb02313_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: keeper_subservice keeper_subservice_clean_type_id_8df3b20e_fk_keeper_cleantype_id; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.keeper_subservice
    ADD CONSTRAINT keeper_subservice_clean_type_id_8df3b20e_fk_keeper_cleantype_id FOREIGN KEY (clean_type_id) REFERENCES public.keeper_cleantype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_onetimepassword main_onetimepassword_user_id_9c93e7df_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_onetimepassword
    ADD CONSTRAINT main_onetimepassword_user_id_9c93e7df_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_user_groups main_user_groups_group_id_a337ba62_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_user_groups
    ADD CONSTRAINT main_user_groups_group_id_a337ba62_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_user_groups main_user_groups_user_id_df502602_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_user_groups
    ADD CONSTRAINT main_user_groups_user_id_df502602_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_user_user_permissions main_user_user_permi_permission_id_cd2b56a3_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_user_user_permissions
    ADD CONSTRAINT main_user_user_permi_permission_id_cd2b56a3_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_user_user_permissions main_user_user_permissions_user_id_451ce57f_fk_main_user_id; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.main_user_user_permissions
    ADD CONSTRAINT main_user_user_permissions_user_id_451ce57f_fk_main_user_id FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_main_user; Type: FK CONSTRAINT; Schema: public; Owner: keeper
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_main_user FOREIGN KEY (user_id) REFERENCES public.main_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

